import type { Metadata } from "next";
import {  Open_Sans } from "next/font/google";

import "./globals.css";

const OpenSans = Open_Sans({
  variable: "--font-Open_Sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${OpenSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
